INSERT INTO tags (name) VALUES ('php');
INSERT INTO tags (name) VALUES ('nginx');

INSERT INTO posts (title, text) VALUES ('test title', $$
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce consectetuer risus a nunc. Nulla pulvinar eleifend sem. Nullam dapibus fermentum ipsum. Fusce suscipit libero eget elit. Aliquam erat volutpat. Sed convallis magna eu sem. Maecenas aliquet accumsan leo. Aliquam ante. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Maecenas lorem. Nam sed tellus id magna elementum tincidunt. Duis pulvinar.
Nulla est. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Nulla pulvinar eleifend sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Vivamus ac leo pretium faucibus. Etiam posuere lacus quis dolor. Phasellus rhoncus. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Suspendisse sagittis ultrices augue. In enim a arcu imperdiet malesuada. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Duis viverra diam non justo. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Integer imperdiet lectus quis justo. Cras elementum. Nunc auctor.
Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Curabitur sagittis hendrerit ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla quis diam. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Aliquam ante. Cras pede libero, dapibus nec, pretium sit amet, tempor quis.
Maecenas sollicitudin. Nullam at arcu a est sollicitudin euismod. Proin in tellus sit amet nibh dignissim sagittis. Nullam dapibus fermentum ipsum. Pellentesque arcu. Duis risus. Nulla quis diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nulla pulvinar eleifend sem. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Integer vulputate sem a nibh rutrum consequat. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Phasellus rhoncus. Quisque porta. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Proin in tellus sit amet nibh dignissim sagittis.
Integer malesuada. Aliquam erat volutpat. Etiam commodo dui eget wisi. In dapibus augue non sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Etiam bibendum elit eget erat. Pellentesque ipsum. Mauris dictum facilisis augue. Integer pellentesque quam vel velit. Pellentesque arcu. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Nulla non arcu lacinia neque faucibus fringilla. Mauris dictum facilisis augue. In rutrum.
Praesent vitae arcu tempor neque lacinia pretium. Mauris tincidunt sem sed arcu. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Integer pellentesque quam vel velit. Integer tempor. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Pellentesque ipsum. Donec quis nibh at felis congue commodo. In convallis. Vivamus luctus egestas leo. Etiam neque. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Integer tempor. Maecenas aliquet accumsan leo. Sed convallis magna eu sem. Nullam rhoncus aliquam metus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Et harum quidem rerum facilis est et expedita distinctio. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Praesent vitae arcu tempor neque lacinia pretium. Etiam posuere lacus quis dolor. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Etiam egestas wisi a erat. Nullam dapibus fermentum ipsum. Morbi scelerisque luctus velit. In enim a arcu imperdiet malesuada.
$$);

INSERT INTO post_tags (post_id, tag_id, position) VALUES (1, 1, 1);
INSERT INTO post_tags (post_id, tag_id, position) VALUES (1, 2, 2);
